# Generated by Django 5.2 on 2025-05-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.CharField(default='TEMP_PRODUCT', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_id',
            field=models.CharField(default='TEMP_VARIANT', max_length=50),
        ),
    ]
