# version: '3.8'

services:
  typesense:
    image: typesense/typesense:0.25.1
    ports:
      - "8108:8108"
    command: ["--data-dir", "/data", "--api-key", "NJU1ovgpuxrf440jV7WdTSBVvB2YaycR", "--enable-cors"]
    volumes:
      - ./typesense-data:/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - typesense
      - db
      - mongodb
    environment:
      TYPESENSE_API_KEY: NJU1ovgpuxrf440jV7WdTSBVvB2YaycR
      TYPESENSE_HOST: typesense

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pgdata:
  mongo_data: