# Generated by Django 5.2 on 2025-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_id',
            field=models.CharField(default='TEMP_VARIANT', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(max_length=50),
        ),
    ]
