# Generated by Django 5.2 on 2025-05-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_products_remove_orderitem_product_and_more'),
        ('products', '0001_initial'),
        ('store', '0005_alter_cartitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
